### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by tomMoulard** [kvtools/valkeyrie#65]
Here's a list of targets in not particular order:

- [x] `supportedBackend` needs to be updated (fixed by #67)
- [x] `Context.Context` store support (#43)
- [x] Change errors messages / types
- [x] Clean unused errors
- [x] Break down store configurations
- [x] Review `.golanci.yml` issues
- [x] Decide what to do with `github.com/kvtools/valkeyrie/store/mock` (use [Mocktail](https://github.com/traefik/mocktail)?)
- [x] merge or close the current PRs?
